# Problem 1 

In [1]:
# 1 - numpy kütüphanesini import edin
import numpy as np


# 2 - 5 elemanlı bir numpy array oluşturun
yetgen = np.array([32,99,105,85])
print(yetgen)

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
yetgen2 = np.sort(yetgen)
print(yetgen2)

# 2 - 5 elemanlı bir numpy array oluşturun
yetgen = np.array([32,99,105,85])
print(yetgen)

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
yetgen2 = np.sort(yetgen)
print(yetgen2)

[ 32  99 105  85]
[ 32  85  99 105]
[ 32  99 105  85]
[ 32  85  99 105]


In [2]:
# 1 - numpy kütüphanesini import edin
import numpy


# 2 - 5 elemanlı bir numpy array oluşturun
yetgen = np.array([32,99,105,85])
print(yetgen)

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
yetgen2 = np.sort(yetgen)
print(yetgen2)

[ 32  99 105  85]
[ 32  85  99 105]


# Problem 2

In [5]:
# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
sayi = np.array([10,15,30,45,60])
print("sayi arrayı:" , sayi)

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
sayi2 = np.arange(5,16)
print("sayi2 arrayi:" , sayi2)
 
# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
sayi3 = np.arange(50,101,5)
print("sayi3 arrayı:" , sayi3)

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
sayi4 = np.zeros(10)
print("sayi4 arrayı:" , sayi4)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
sayi5 = np.ones(8)
print("sayi5 arrayı:" , sayi5)

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
sayi6 = np.linspace(0,100,5)
print("sayi6 arrayı:" , sayi6)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
sayi7 = np.random.randint(10,31,size=5)
print("sayi7 arrayı:" , sayi7)

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
random = np.random.uniform(-1,1, size=10)
print("random sayılar:" , random)

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
random2 = np.random.randint(10,50, size=(3,5))
print("random2:" , random2)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
print(random2.sum(axis=0))
print(random2.sum(axis=1))

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
print(random2.max())
print(random2.min())
print(random2.mean())

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
print(random.argmax())


# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
random4 = np.random.randint(10,20, size=10)
print(random4[:3])

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print(random4[::-1])

# 15- Üretilen matrisin ilk satırını seçiniz.
print(random2[0])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print(random2[1][2])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print(random2[:,0])

# 18- Üretilen matrisin her bir elemanının karesini alınız.
print(random2**2)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
random6 = np.random.randint(-50,50, size=(4,5))
print((random6 % 2 == 0) & (random6 > 0))


sayi arrayı: [10 15 30 45 60]
sayi2 arrayi: [ 5  6  7  8  9 10 11 12 13 14 15]
sayi3 arrayı: [ 50  55  60  65  70  75  80  85  90  95 100]
sayi4 arrayı: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
sayi5 arrayı: [1. 1. 1. 1. 1. 1. 1. 1.]
sayi6 arrayı: [  0.  25.  50.  75. 100.]
sayi7 arrayı: [19 30 15 16 16]
random sayılar: [-0.19898543  0.53943031  0.02130932  0.12301305 -0.54460677  0.15223495
  0.12039205 -0.68022967 -0.33090919  0.91855462]
random2: [[20 35 33 36 13]
 [39 45 48 35 45]
 [13 32 34 14 34]]
[ 72 112 115  85  92]
[137 212 127]
48
13
31.733333333333334
9
[13 16 17]
[13 11 12 13 15 14 11 17 16 13]
[20 35 33 36 13]
48
[20 39 13]
[[ 400 1225 1089 1296  169]
 [1521 2025 2304 1225 2025]
 [ 169 1024 1156  196 1156]]
[[ True False  True  True  True]
 [ True False False False False]
 [ True  True  True False False]
 [False False False False False]]
